import { existsSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { CAPTAIN_NAV_ITEMS } from '@/lib/captain/nav';

// =============================================================================
// HVA-331: the admin -> captain portal must not advertise a route it lacks
// =============================================================================
//
// The impersonation nav is generated by rewriting every CAPTAIN_NAV_ITEMS href
// from `/captain/x` to `/admin/portal/<id>/x`. That rewrite assumed each
// captain page had a mirror. Three never did — Dispatch (added by HVA-308 and
// never mirrored), Tasks and Tickets — so the nav rendered three links that
// landed on the 404 page.
//
// This is the guard the drift needed. It reads the filesystem rather than
// trusting a hand-kept list, so the next captain section that ships without a
// mirror fails here instead of shipping a dead link. Fixing the failure is a
// choice of two one-line edits: add the route, or flag the item
// `noAdminPortalRoute` so the layout renders it disabled.
// =============================================================================

const PORTAL_DIR = join(
  process.cwd(),
  'app',
  'admin',
  'portal',
  '[captainId]',
);

function mirrorPageExists(captainHref: string): boolean {
  const segment = captainHref.replace(/^\/captain\//, '');
  return existsSync(join(PORTAL_DIR, segment, 'page.tsx'));
}

describe('admin -> captain portal nav', () => {
  it.each(CAPTAIN_NAV_ITEMS.filter((i) => !i.noAdminPortalRoute))(
    'renders $label as a link, so its mirror route must exist',
    (item) => {
      expect(mirrorPageExists(item.href)).toBe(true);
    },
  );

  it.each(CAPTAIN_NAV_ITEMS.filter((i) => i.noAdminPortalRoute))(
    '$label is flagged as unmirrored, so it must genuinely have no route',
    (item) => {
      // Stops the flag outliving the gap: once someone builds
      // /admin/portal/[captainId]/dispatch, this fails until the flag comes
      // off and the item becomes a real link again.
      expect(mirrorPageExists(item.href)).toBe(false);
    },
  );

  it('flags exactly the three known gaps and nothing else', () => {
    const flagged = CAPTAIN_NAV_ITEMS.filter((i) => i.noAdminPortalRoute).map(
      (i) => i.href,
    );
    expect(flagged.sort()).toEqual([
      '/captain/dispatch',
      '/captain/tasks',
      '/captain/tickets',
    ]);
  });
});
